### ISSUE TITLE
It does not seem compatible with mkdocs 1.* anymore

### ISSUE THREAD

**Issue by veremenko-y** [ovasquez/mkdocs-merge#10]
It fails on "nav" section and does not apply "custom_dir" theme properly.

**Comment by ovasquez** [comment]
Thanks for reporting the issue, I will take a look at this soon, as I want this to remain compatible with the most recent versions of MkDocs.

**Comment by veremenko-y** [comment]
Thank you for maintaining the project. I rolled back for now as it is not urgent for me to be on the latest mkdocs.

**Comment by ovasquez** [comment]
@veremenko-y I just published a new version, could you confirm it now works for MkDocs >= 1.0?

**Comment by veremenko-y** [comment]
I converted the configs to new format, fixed the theme. And `mkdocs-merge` worked flawlessly. Thank you for a quick fix.
